#' FIAs weighting algorithm
#'
#' Weighting the top three FIAs to achieve performance improvement.
#'
#' @param data The result list generated by FIAs() is used as the input of FIAs_W().
#' @param top_n Numeric format, its value is between 1:n_features, where n_features is the corresponding parameter of FIAs(). FIAs_W() will generate a new feature ranking based on the fluctuating weights, and top_n determines that FIAs_W() will dynamically select features between 1:top_n and compare the rsq indicator to find the corresponding weight.
#' @param weight_step Numeric format, determines the step size when traversing weights.
#' @param output_file File name ending with .xlsx, output weight results, optimal weight, cross-validation performance, feature ranking, time, and memory usage.
#'
#' @details
#' This function enhances feature selection by weighting the top three feature importance algorithms (FIAs) obtained from FIAs(). It dynamically combines their rankings using varying weights within a specified range, evaluates model performance (R²) via cross-validation for each weight combination on the top features up to \code{top_n}, and selects the optimal weights that maximize predictive accuracy. Subsequently, incremental feature selection (IFS) is conducted on the weighted ranking to determine the final informative feature subset. The output includes optimal weights, performance metrics, feature rankings, runtime, and memory usage.
#'
#' @return A list with three components:
#' \describe{
#'   \item{\code{data}}{The input data frame.}
#'   \item{\code{parameters}}{A list of input parameters and settings.}
#'   \item{\code{results}}{A list of results from each specified feature importance algorithm, including ranked features and model objects.}
#' }
#'Compared with the result obtained by FIAs(), the FIAs_W algorithm is added to the result.
#'
#' @examples
#' \dontrun{
#' FIAs_result <- FIAs(
#'   data = WW1768,
#'   gwas.myY = gwas.myY,
#'   gwas.myGM = gwas.myGM,
#'   n_folds = 10,
#'   n_features = 500,
#'   ridge.lambda = 1:300,
#'   algorithms = c("mrmr", "PVE", "Cor", "RF", "ridge", "gwas")
#' )
#' FIAs_W_result <- FIAs_W(data = FIAs_result,weight_step = 0.1)
#' rank_fias(FIAs_W_result)
#' }
#'
#' @seealso \code{\link{FIAs},\link{rank_fias}}
#'
#' @export
FIAs_W <- function(data, top_n = NULL, weight_step = 0.5, output_file = "FIAs_W.xlsx") {
  `%>%` <- magrittr::`%>%`
  start_time <- Sys.time(); gc(); start_mem <- pryr::mem_used()

  target <- names(data$data)[1]
  params <- data$parameters
  metrics <- params$metrics; k_folds <- params$n_folds; n_features <- params$n_features; seed <- params$seed

  ranking_result <- rank_fias(data)
  feature_df <- ranking_result$feature_rank_matrix %>%
    tibble::rownames_to_column("feature") %>%
    dplyr::mutate(dplyr::across(2:4, as.numeric))

  top3_algos <- colnames(ranking_result$feature_rank_matrix)
  if (is.null(top_n)) {
    top_n <- ceiling(length(data$data) / 2)
    message("\ntop_n = ", top_n)
  }

  weighted_ranks <- function(weights) {
    feature_df %>%
      dplyr::mutate(weighted_rank = Reduce(`+`, Map(`*`, weights, .[top3_algos]))) %>%
      dplyr::select(feature, weighted_rank)
  }

  evaluate_performance <- function(weights) {
    set.seed(seed)
    feats <- weighted_ranks(weights) %>% dplyr::arrange(weighted_rank) %>%
      dplyr::slice(1:top_n) %>% dplyr::pull(feature)
    FIAs_W_tk <- data$data %>% dplyr::select(1, all_of(feats))
    task <- mlr3::as_task_regr(FIAs_W_tk, target = target,task_id = "task")
    rr <- mlr3::resample(task, mlr3::lrn("regr.ranger"), mlr3::rsmp("cv", folds = k_folds))
    rr$aggregate(mlr3::msr("regr.rsq"))
  }

  w_vals <- seq(0, 1, by = weight_step)
  grid <- expand.grid(w1 = w_vals, w2 = w_vals) %>%
    dplyr::mutate(w3 = 1 - w1 - w2) %>% dplyr::filter(w3 >= 0)
  message(sprintf("\nWith step %.3f, %d weight combinations generated.", weight_step, nrow(grid)))

  W_n <- paste0(top3_algos, "_weight")
  results <- purrr::map_dfr(seq_len(nrow(grid)), function(i) {
    w <- unlist(grid[i, ])
    rsq <- evaluate_performance(w)
    elapsed <- Sys.time() - start_time
    elapsed_min <- as.numeric(elapsed, units = "mins")
    avg_iter <- elapsed_min / i
    remaining_iters <- nrow(grid) - i
    remain_min <- avg_iter * remaining_iters
    message(sprintf("Iter %d/%d: w=%.2f,%.2f,%.2f | R²=%.3f | Elapsed: %.2f min | Est. Remaining: %.2f min",
                    i, nrow(grid), w[1], w[2], w[3], rsq,
                    elapsed_min, remain_min))
    named_w <- setNames(as.list(w), W_n)
    tib <- tibble::as_tibble(named_w)
    tib$rsq <- rsq; tib
  })

  best_idx <- which.max(results$rsq)
  best_weights <- as.numeric(results[best_idx, 1:3])
  names(best_weights) <- top3_algos

  feature_df <- feature_df %>%
    dplyr::mutate(weighted_rank = Reduce(`+`, Map(`*`, best_weights, .[top3_algos]))) %>%
    dplyr::arrange(weighted_rank)

  max_features <- min(n_features, ncol(data$data) - 1)
  score_list <- vector("list", max_features)
  agg_list <- vector("list", max_features)

  message("\n Running cross-validation with optimal weights...")
  for (count in seq_len(max_features)) {
    set.seed(seed)
    feats <- feature_df$feature[1:count]
    FIAs_W_IFs <- data$data %>% dplyr::select(1, all_of(feats))
    task <- mlr3::as_task_regr(FIAs_W_IFs, target = target)
    rr <- mlr3::resample(task, mlr3::lrn("regr.ranger"), mlr3::rsmp("cv", folds = k_folds))
    score_list[[count]] <- rr$score(mlr3::msrs(metrics)) %>% tibble::as_tibble() %>%
      dplyr::mutate(gradient = count, algorithm = "FIAs-W")
    agg_list[[count]] <- rr$aggregate(mlr3::msrs(metrics)) %>% as.list() %>%
      tibble::as_tibble() %>% dplyr::mutate(gradient = count, algorithm = "FIAs-W")
  }

  ensemble_scores <- data.table::rbindlist(score_list, fill = TRUE) %>% dplyr::select(c(algorithm, gradient, iteration, learner_id), any_of(c("rsq",metrics)))
  ensemble_aggregates <- data.table::rbindlist(agg_list, fill = TRUE) %>% dplyr::select(c(algorithm, gradient), any_of(c("rsq",metrics)))
  optimal_k <- ensemble_aggregates[which.max(ensemble_aggregates$rsq), "gradient"][[1]]
  feature_selection <- head(feature_df$feature, optimal_k)

  end_time <- Sys.time(); gc(); end_mem <- pryr::mem_used()
  data$results$FIAs_W <- list(
    model = list(weights = best_weights),
    scores = ensemble_scores,
    aggregates = ensemble_aggregates,
    feature_selection = feature_selection,
    feature_ranking = feature_df$feature,
    time_mins = round(as.numeric(difftime(end_time, start_time, units = "mins")), 3),
    memory_bytes = end_mem - start_mem
  )

  writexl::write_xlsx(list(
    "Weight Results" = results,
    "Best Weights" = tibble::tibble(Algorithm = top3_algos, Weight = best_weights),
    "FIAs_W Scores" = as.data.frame(ensemble_scores),
    "FIAs_W Aggregates" = as.data.frame(ensemble_aggregates),
    "Feature Ranking" = feature_df,
    "time_memory" = tibble::tibble(time_mins = data$results$FIAs_W$time_mins,
                                   memory_bytes = data$results$FIAs_W$memory_bytes)
  ), path = output_file)

  message("\nResults saved to: ", normalizePath(output_file))
  return(data)
}


