#' Plot the performance evolution of GWO/PGWO feature selection
#'
#' `gwo_plot()` visualizes the performance evolution over iterations for results
#' generated by \code{\link{gwo_fs}}.It shows the trends of mean R², median R²,
#' and maximum R² across generations,allowing users to evaluate the convergence behavior
#' of the Grey Wolf Optimizer (GWO)  or Priority-Guided Grey Wolf Optimizer (PGWO) in the feature selection process.
#'
#' @param data A list returned by \code{gwo_fs()}, containing at least the element
#'   \code{performance}, a data frame with columns \code{iteration} and \code{regr.rsq}.
#'
#' @return A ggplot2 object showing three lines—mean, median, and max R²—across GWO/PGWO iterations.
#'
#' @seealso \code{\link{gwo_fs}}
#'
#' @examples
#' \dontrun{
#' union <- feature_union(FIAs_W_result$results$FIAs_W,abess_result,Boruta_result,PL_result,EN_result,mmpc_result,data = WW1768)
#' feature_union <- union$union_features
#' GWO_result <- gwo_fs(
#'   data = WW1768,
#'   feature_cols = feature_union,
#'   seed = 1,
#'   control = list(numPopulation = 10, maxIter = 20, elite = 1),
#'   output_file = "GWO.csv"
#' )
#'
#' gwo_plot(GWO_result)
#' }
#'
#' @export
gwo_plot <- function(data) {
  `%>%` <- magrittr::`%>%`
  stats_per_iteration <- data$performance %>%
    dplyr::group_by(iteration) %>%
    dplyr::summarise(
      max_rsq = max(regr.rsq),
      median_rsq = median(regr.rsq),
      mean_rsq = mean(regr.rsq),
      .groups = "drop"
    )
  max_row <- stats_per_iteration[which.max(stats_per_iteration$max_rsq), ]
  max_value <- round(max_row$max_rsq, 3)
  max_gen <- max_row$iteration
  min_value <- min(stats_per_iteration$median_rsq)
  y_range <- range(c(stats_per_iteration$mean_rsq,
                     stats_per_iteration$median_rsq,
                     stats_per_iteration$max_rsq), na.rm = TRUE)
  y_gap <- diff(y_range) * 0.03

  ggplot2::ggplot(stats_per_iteration, ggplot2::aes(x = iteration)) +
    ggplot2::geom_line(ggplot2::aes(y = mean_rsq, color = "mean"), linewidth = 0.5) +
    ggplot2::geom_line(ggplot2::aes(y = median_rsq, color = "median"), linewidth = 0.5) +
    ggplot2::geom_line(ggplot2::aes(y = max_rsq, color = "max"), linewidth = 0.5) +
    ggplot2::labs(x = "generation", y = expression(R^2)) +
    ggplot2::scale_color_manual(
      name = NULL,
      values = c("mean" = "#E31A1C", "median" = "#1F78B4", "max" = "#FDBF6F")
    ) +
    ggplot2::annotate("text",
                      x = 0,y = min_value+4*y_gap,
                      label = paste0("max R²: ", max_value),
                      hjust = 0, vjust = -1,
                      size = 4, color = "black") +
    ggplot2::annotate("text",
                      x = 0,y = min_value+y_gap,
                      label = paste0("generation: ", max_gen),
                      hjust = 0, vjust = -1,
                      size = 4, color = "black") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = c(0.8, 0.18),
      legend.background = ggplot2::element_blank(),
      legend.key.size = grid::unit(1.4, "lines"),
      legend.text = ggplot2::element_text(size = 10)
    )
}

