#' Ranking Feature Selection Algorithms and Their Feature Rankings from FIAs or FIAs_W Results
#'
#' Rank the results of FIAs according to "regr.rsq" and show the top three algorithms and feature rankings.
#'
#' @param data The result list generated by `FIAs()` or `FIAs_W()` is used as the input of `rank_fias()`.
#'
#' @return A list with three components:
#' \describe{
#'   \item{\code{Performance_ranking}}{A data frame summarizing the prediction performance of each feature selection algorithm, including the maximum R² value and the number of features used.}
#'   \item{\code{feature_rank_matrix}}{A data frame showing the feature ranking results for each algorithm. Each column corresponds to an algorithm, and each row gives the rank of a specific feature.}
#'   \item{\code{metadata}}{A list containing metadata information, including the generation timestamp, the total number of features ranked, and the list of algorithms used.}
#' }
#'
#' @details
#' This function takes the output list from `FIAs()` or `FIAs_W()`, which contains
#' the results of multiple feature selection algorithms evaluated on regression tasks.
#' It ranks these algorithms based on their maximum cross-validated R² values ("regr.rsq"),
#' then extracts and summarizes the top three algorithms in terms of prediction performance.
#'
#' Specifically, it:
#' \itemize{
#'   \item Verifies the input data structure and necessary components.
#'   \item Extracts the maximum R² and corresponding number of features used by each algorithm.
#'   \item Sorts algorithms descendingly by their maximum R² value to determine performance ranking.
#'   \item Constructs a feature ranking matrix for the top three algorithms, where each column
#'   represents an algorithm and each row represents a feature's rank within that algorithm.
#' }
#'
#' The output provides a comprehensive overview of algorithm performance and feature importance rankings,
#' facilitating comparison and interpretation of feature selection results across multiple methods.
#'
#' @examples
#' \dontrun{
#' FIAs_result <- FIAs(
#'   data = WW1768,
#'   gwas.myY = gwas.myY,
#'   gwas.myGM = gwas.myGM,
#'   n_folds = 10,
#'   n_features = 500,
#'   ridge.lambda = 1:300,
#'   algorithms = c("mrmr", "PVE", "Cor", "RF", "ridge", "gwas")
#' )
#' rank_fias(data = FIAs_result)
#'
#' FIAs_W_result <- FIAs_W(data = FIAs_result,weight_step = 0.1)
#' rank_fias(data = FIAs_W_result)
#' }
#'
#' @seealso \code{\link{FIAs},\link{FIAs_W}}
#'
#' @export
rank_fias <- function(data) {
  `%>%` <- magrittr::`%>%`
  if (!"results" %in% names(data)) stop("Missing results component")
  if (!all(sapply(data$results, function(x) "feature_ranking" %in% names(x)))) {
    stop("All result components must contain feature_ranking")
  }

  algo_names <- names(data$results)
  algo_stats <- lapply(algo_names, function(name) {
    agg <- data$results[[name]]$aggregates
    if (!all(c("rsq", "gradient") %in% colnames(agg))) {
      stop(paste("Missing required columns in", name, "aggregates"))
    }

    max_rsq <- max(agg$rsq, na.rm = TRUE)
    max_index <- which.max(agg$rsq)
    grad_value <- agg$gradient[max_index]

    data.frame(
      algorithm = name,
      max_rsq = round(max_rsq, 4),
      n = grad_value
    )
  })

  ranking_df <- do.call(rbind, algo_stats) %>%
    dplyr::arrange(desc(max_rsq))

  message("====== Algorithm Performance Ranking ======")
  rank_strings <- sprintf("%s (n=%d, R²=%.3f)",
                          ranking_df$algorithm,
                          ranking_df$n,
                          ranking_df$max_rsq)
  message(paste(rank_strings, collapse = "\n"))

  if (length(data$results) < 3) {
    stop("At least three feature selection models are required")
  }

  top3_algos <- head(ranking_df$algorithm, 3)
  create_rank_matrix <- function(algo_list) {

    all_features <- unique(unlist(algo_list))

    rank_mat <- matrix(
      NA,
      nrow = length(all_features),
      ncol = length(algo_list),
      dimnames = list(all_features, names(algo_list))
    )

    for (i in seq_along(algo_list)) {
      features <- algo_list[[i]]
      rank_mat[features, i] <- 1:length(features)
    }

    as.data.frame(rank_mat)
  }

  feature_rank_matrix <- create_rank_matrix(
    setNames(
      lapply(top3_algos, function(x) data$results[[x]]$feature_ranking),
      top3_algos
    )
  )

  message("\n=== Feature Ranking Matrix (Top 10 Features) ===")
  print(head(feature_rank_matrix, 10))

  invisible(list(
    Performance_ranking = ranking_df,
    feature_rank_matrix = feature_rank_matrix,
    metadata = list(
      generated = Sys.time(),
      num_features = nrow(feature_rank_matrix),
      algorithms = top3_algos
    )
  ))
}
